[2025-08-03T10:24:15.835+0000] {processor.py:157} INFO - Started process (PID=171) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:24:15.838+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:24:15.842+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:24:15.841+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:24:16.150+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:24:16.143+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:24:16.178+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:24:16.224+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.401 seconds
[2025-08-03T10:24:46.435+0000] {processor.py:157} INFO - Started process (PID=179) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:24:46.437+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:24:46.438+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:24:46.438+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:24:46.561+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:24:46.554+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:24:46.563+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:24:46.606+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.176 seconds
[2025-08-03T10:25:16.800+0000] {processor.py:157} INFO - Started process (PID=190) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:25:16.804+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:25:16.805+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:25:16.805+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:25:16.977+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:25:16.965+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:25:16.979+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:25:17.051+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.264 seconds
[2025-08-03T10:25:47.182+0000] {processor.py:157} INFO - Started process (PID=207) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:25:47.278+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:25:47.281+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:25:47.280+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:25:47.443+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:25:47.434+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:25:47.446+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:25:47.495+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.319 seconds
[2025-08-03T10:27:52.729+0000] {processor.py:157} INFO - Started process (PID=224) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:27:52.895+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:27:52.938+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:27:52.908+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:27:54.232+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:27:54.214+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:27:54.237+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:27:54.398+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 9.203 seconds
[2025-08-03T10:28:24.639+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:28:24.642+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:28:24.648+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:28:24.646+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:28:25.797+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:28:25.787+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:28:25.800+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:28:25.874+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 1.138 seconds
[2025-08-03T10:28:56.066+0000] {processor.py:157} INFO - Started process (PID=270) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:28:56.068+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:28:56.069+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:28:56.069+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:28:56.160+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:28:56.153+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:28:56.163+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:28:56.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.131 seconds
[2025-08-03T10:29:26.340+0000] {processor.py:157} INFO - Started process (PID=290) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:29:26.342+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:29:26.344+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:29:26.344+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:29:26.453+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:29:26.447+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:29:26.455+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:29:26.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.157 seconds
[2025-08-03T10:29:57.356+0000] {processor.py:157} INFO - Started process (PID=301) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:29:57.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:29:57.382+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:29:57.381+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:29:57.650+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:29:57.631+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:29:57.659+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:29:57.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.374 seconds
[2025-08-03T10:30:28.659+0000] {processor.py:157} INFO - Started process (PID=321) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:30:28.677+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:30:28.679+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:30:28.678+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:30:28.815+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:30:28.806+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:30:28.819+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:30:28.851+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.200 seconds
[2025-08-03T10:30:58.999+0000] {processor.py:157} INFO - Started process (PID=332) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:30:59.000+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:30:59.002+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:30:59.001+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:30:59.173+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:30:59.126+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:30:59.177+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:30:59.213+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.220 seconds
[2025-08-03T10:31:29.352+0000] {processor.py:157} INFO - Started process (PID=352) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:31:29.353+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:31:29.356+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:31:29.354+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:31:29.579+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:31:29.552+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:31:29.581+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:31:29.653+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.313 seconds
[2025-08-03T10:31:59.730+0000] {processor.py:157} INFO - Started process (PID=363) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:31:59.731+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:31:59.733+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:31:59.732+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:31:59.879+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:31:59.869+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:31:59.881+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:31:59.923+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.198 seconds
[2025-08-03T10:32:30.827+0000] {processor.py:157} INFO - Started process (PID=383) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:32:30.829+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:32:30.830+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:32:30.830+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:32:30.991+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:32:30.983+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:32:30.993+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:32:31.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.206 seconds
[2025-08-03T10:33:01.120+0000] {processor.py:157} INFO - Started process (PID=396) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:33:01.122+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:33:01.123+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:33:01.123+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:33:01.278+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:33:01.268+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:33:01.281+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:33:01.318+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.203 seconds
[2025-08-03T10:33:31.447+0000] {processor.py:157} INFO - Started process (PID=414) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:33:31.453+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:33:31.455+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:33:31.454+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:33:31.765+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:33:31.754+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:33:31.768+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:33:31.801+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.361 seconds
[2025-08-03T10:34:01.947+0000] {processor.py:157} INFO - Started process (PID=427) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:34:01.949+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:34:01.951+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:34:01.950+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:34:02.090+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:34:02.078+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:34:02.092+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:34:02.132+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.191 seconds
[2025-08-03T10:34:32.313+0000] {processor.py:157} INFO - Started process (PID=445) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:34:32.315+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:34:32.317+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:34:32.316+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:34:32.420+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:34:32.412+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:34:32.422+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:34:32.452+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.143 seconds
[2025-08-03T10:35:02.550+0000] {processor.py:157} INFO - Started process (PID=459) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:35:02.552+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:35:02.554+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:35:02.553+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:35:02.674+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:35:02.666+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:35:02.676+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:35:02.708+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.163 seconds
[2025-08-03T10:35:32.846+0000] {processor.py:157} INFO - Started process (PID=476) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:35:32.848+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:35:32.850+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:35:32.849+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:35:32.943+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:35:32.936+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:35:32.945+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:35:32.976+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.135 seconds
[2025-08-03T10:36:03.041+0000] {processor.py:157} INFO - Started process (PID=490) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:36:03.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:36:03.045+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:36:03.044+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:36:03.143+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:36:03.135+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:36:03.145+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:36:03.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.137 seconds
[2025-08-03T10:36:33.254+0000] {processor.py:157} INFO - Started process (PID=507) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:36:33.256+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:36:33.258+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:36:33.257+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:36:33.350+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:36:33.344+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:36:33.353+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:36:33.383+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.134 seconds
[2025-08-03T10:37:03.474+0000] {processor.py:157} INFO - Started process (PID=521) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:37:03.476+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:37:03.478+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:37:03.477+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:37:03.584+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:37:03.575+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:37:03.586+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:37:03.616+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.148 seconds
[2025-08-03T10:37:33.705+0000] {processor.py:157} INFO - Started process (PID=538) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:37:33.707+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:37:33.709+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:37:33.708+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:37:33.844+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:37:33.833+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:37:33.847+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:37:33.888+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.188 seconds
[2025-08-03T10:38:04.019+0000] {processor.py:157} INFO - Started process (PID=554) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:38:04.021+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:38:04.022+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:38:04.022+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:38:04.130+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:38:04.123+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:38:04.132+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:38:04.162+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.149 seconds
[2025-08-03T10:38:34.763+0000] {processor.py:157} INFO - Started process (PID=569) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:38:34.765+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:38:34.766+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:38:34.766+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:38:34.881+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:38:34.872+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:38:34.884+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:38:34.923+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.166 seconds
[2025-08-03T10:39:05.088+0000] {processor.py:157} INFO - Started process (PID=586) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:39:05.090+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:39:05.092+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:39:05.092+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:39:05.241+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:39:05.225+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:39:05.244+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:39:05.282+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.204 seconds
[2025-08-03T10:39:35.456+0000] {processor.py:157} INFO - Started process (PID=600) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:39:35.458+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:39:35.459+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:39:35.459+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:39:35.563+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:39:35.551+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:39:35.566+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:39:35.595+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.144 seconds
[2025-08-03T10:40:05.703+0000] {processor.py:157} INFO - Started process (PID=617) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:40:05.705+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:40:05.706+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:40:05.706+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:40:05.819+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:40:05.811+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:40:05.822+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:40:05.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.159 seconds
[2025-08-03T10:40:35.964+0000] {processor.py:157} INFO - Started process (PID=631) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:40:35.966+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:40:35.967+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:40:35.967+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:40:36.073+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:40:36.065+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:40:36.076+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:40:36.107+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.148 seconds
[2025-08-03T10:41:06.247+0000] {processor.py:157} INFO - Started process (PID=648) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:41:06.249+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:41:06.250+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:41:06.250+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:41:06.406+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:41:06.390+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:41:06.408+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:41:06.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.207 seconds
[2025-08-03T10:41:36.593+0000] {processor.py:157} INFO - Started process (PID=662) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:41:36.594+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:41:36.596+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:41:36.595+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:41:36.704+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:41:36.697+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:41:36.706+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:41:36.734+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.146 seconds
[2025-08-03T10:42:06.818+0000] {processor.py:157} INFO - Started process (PID=679) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:42:06.819+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:42:06.821+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:42:06.820+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:42:06.971+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:42:06.942+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:42:06.979+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:42:07.016+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.204 seconds
[2025-08-03T10:42:37.161+0000] {processor.py:157} INFO - Started process (PID=693) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:42:37.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:42:37.166+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:42:37.165+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:42:37.321+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:42:37.316+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:42:37.324+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:42:37.352+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.198 seconds
[2025-08-03T10:43:07.464+0000] {processor.py:157} INFO - Started process (PID=713) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:43:07.466+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:43:07.468+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:43:07.467+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:43:07.573+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:43:07.566+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:43:07.575+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:43:07.606+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.147 seconds
[2025-08-03T10:43:37.714+0000] {processor.py:157} INFO - Started process (PID=727) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:43:37.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:43:37.717+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:43:37.716+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:43:37.828+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:43:37.820+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:43:37.830+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:43:37.861+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.152 seconds
[2025-08-03T10:44:07.965+0000] {processor.py:157} INFO - Started process (PID=746) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:44:07.967+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:44:07.968+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:44:07.968+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:44:08.077+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:44:08.069+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:44:08.079+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:44:08.112+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.152 seconds
[2025-08-03T10:44:38.215+0000] {processor.py:157} INFO - Started process (PID=755) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:44:38.216+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:44:38.218+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:44:38.217+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:44:38.327+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:44:38.319+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:44:38.329+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:44:38.360+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.151 seconds
[2025-08-03T10:45:08.484+0000] {processor.py:157} INFO - Started process (PID=772) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:45:08.486+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:45:08.487+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:45:08.487+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:45:08.587+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:45:08.579+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:45:08.589+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:45:08.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.138 seconds
[2025-08-03T10:45:38.710+0000] {processor.py:157} INFO - Started process (PID=783) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:45:38.716+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:45:38.717+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:45:38.717+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:45:38.827+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:45:38.820+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:45:38.830+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:45:38.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.161 seconds
[2025-08-03T10:46:08.965+0000] {processor.py:157} INFO - Started process (PID=803) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:46:08.967+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:46:08.969+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:46:08.969+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:46:09.078+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:46:09.071+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:46:09.080+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:46:09.108+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.147 seconds
[2025-08-03T10:46:39.173+0000] {processor.py:157} INFO - Started process (PID=817) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:46:39.175+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:46:39.177+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:46:39.176+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:46:39.273+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:46:39.267+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:46:39.276+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:46:39.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.136 seconds
[2025-08-03T10:47:09.426+0000] {processor.py:157} INFO - Started process (PID=837) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:47:09.428+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:47:09.429+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:47:09.429+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:47:09.531+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:47:09.524+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:47:09.534+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:47:09.562+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.141 seconds
[2025-08-03T10:47:39.675+0000] {processor.py:157} INFO - Started process (PID=851) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:47:39.677+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:47:39.678+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:47:39.678+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:47:39.779+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:47:39.772+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:47:39.781+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:47:39.810+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.140 seconds
[2025-08-03T10:48:09.920+0000] {processor.py:157} INFO - Started process (PID=874) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:48:09.922+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:48:09.924+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:48:09.924+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:48:10.028+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:48:10.020+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:48:10.030+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:48:10.057+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.142 seconds
[2025-08-03T10:48:40.160+0000] {processor.py:157} INFO - Started process (PID=885) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:48:40.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:48:40.166+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:48:40.165+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:48:40.280+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:48:40.271+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:48:40.282+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:48:40.314+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.162 seconds
[2025-08-03T10:49:10.429+0000] {processor.py:157} INFO - Started process (PID=905) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:49:10.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:49:10.432+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:49:10.432+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:49:10.536+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:49:10.528+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:49:10.538+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:49:10.575+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.151 seconds
[2025-08-03T10:49:40.720+0000] {processor.py:157} INFO - Started process (PID=916) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:49:40.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:49:40.723+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:49:40.722+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:49:40.830+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:49:40.822+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:49:40.833+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:49:40.861+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.146 seconds
[2025-08-03T10:50:10.970+0000] {processor.py:157} INFO - Started process (PID=936) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:50:10.971+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:50:10.973+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:50:10.972+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:50:11.082+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:50:11.074+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:50:11.084+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:50:11.112+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.147 seconds
[2025-08-03T10:50:41.204+0000] {processor.py:157} INFO - Started process (PID=947) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:50:41.206+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:50:41.207+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:50:41.207+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:50:41.318+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:50:41.310+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:50:41.321+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:50:41.351+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.152 seconds
[2025-08-03T10:51:11.484+0000] {processor.py:157} INFO - Started process (PID=967) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:51:11.486+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:51:11.489+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:51:11.488+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:51:11.596+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:51:11.589+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:51:11.598+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:51:11.627+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.147 seconds
[2025-08-03T10:51:41.728+0000] {processor.py:157} INFO - Started process (PID=978) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:51:41.730+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:51:41.731+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:51:41.731+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:51:41.841+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:51:41.833+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:51:41.843+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:51:41.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.149 seconds
[2025-08-03T10:52:11.993+0000] {processor.py:157} INFO - Started process (PID=998) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:52:11.995+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:52:11.997+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:52:11.996+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:52:12.105+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:52:12.098+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:52:12.107+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:52:12.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.149 seconds
[2025-08-03T10:52:42.261+0000] {processor.py:157} INFO - Started process (PID=1009) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:52:42.262+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:52:42.264+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:52:42.263+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:52:42.366+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:52:42.357+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:52:42.369+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:52:42.398+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.142 seconds
[2025-08-03T10:53:12.479+0000] {processor.py:157} INFO - Started process (PID=1029) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:53:12.480+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:53:12.482+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:53:12.481+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:53:12.583+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:53:12.576+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:53:12.586+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:53:12.615+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.141 seconds
[2025-08-03T10:53:42.711+0000] {processor.py:157} INFO - Started process (PID=1040) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:53:42.713+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:53:42.715+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:53:42.714+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:53:42.813+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:53:42.805+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:53:42.815+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:53:42.853+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.146 seconds
[2025-08-03T10:54:12.980+0000] {processor.py:157} INFO - Started process (PID=1060) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:54:12.981+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:54:12.983+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:54:12.983+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:54:13.097+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:54:13.090+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:54:13.099+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:54:13.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.151 seconds
[2025-08-03T10:54:43.213+0000] {processor.py:157} INFO - Started process (PID=1071) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:54:43.214+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:54:43.216+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:54:43.216+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:54:43.334+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:54:43.325+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:54:43.337+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:54:43.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.163 seconds
[2025-08-03T10:55:13.489+0000] {processor.py:157} INFO - Started process (PID=1094) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:55:13.490+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:55:13.492+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:55:13.491+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:55:13.593+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:55:13.586+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:55:13.595+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:55:13.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.139 seconds
[2025-08-03T10:55:43.697+0000] {processor.py:157} INFO - Started process (PID=1105) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:55:43.699+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:55:43.701+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:55:43.701+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:55:43.834+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:55:43.827+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:55:43.836+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:55:43.870+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.178 seconds
[2025-08-03T10:56:14.003+0000] {processor.py:157} INFO - Started process (PID=1125) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:56:14.004+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:56:14.006+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:56:14.005+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:56:14.169+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:56:14.159+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:56:14.171+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:56:14.202+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.205 seconds
[2025-08-03T10:56:44.466+0000] {processor.py:157} INFO - Started process (PID=1136) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:56:44.565+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:56:44.569+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:56:44.567+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:56:44.928+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:56:44.907+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:56:44.933+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:56:45.045+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.588 seconds
[2025-08-03T10:57:15.642+0000] {processor.py:157} INFO - Started process (PID=1156) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:57:15.737+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:57:15.739+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:57:15.738+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:57:15.987+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:57:15.969+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:57:15.991+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:57:16.031+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.395 seconds
[2025-08-03T10:57:46.598+0000] {processor.py:157} INFO - Started process (PID=1167) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:57:46.601+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:57:46.602+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:57:46.602+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:57:46.701+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:57:46.695+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:57:46.704+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:57:46.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.137 seconds
[2025-08-03T10:58:16.962+0000] {processor.py:157} INFO - Started process (PID=1190) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:58:16.966+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:58:16.971+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:58:16.970+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:58:17.121+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:58:17.115+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:58:17.123+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:58:17.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.201 seconds
[2025-08-03T10:58:47.246+0000] {processor.py:157} INFO - Started process (PID=1201) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:58:47.248+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:58:47.249+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:58:47.249+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:58:47.345+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:58:47.337+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:58:47.348+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:58:47.378+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.137 seconds
[2025-08-03T10:59:17.473+0000] {processor.py:157} INFO - Started process (PID=1222) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:59:17.475+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:59:17.476+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:59:17.476+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:59:17.617+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:59:17.607+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:59:17.619+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:59:17.651+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.183 seconds
[2025-08-03T10:59:47.781+0000] {processor.py:157} INFO - Started process (PID=1229) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:59:47.785+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T10:59:47.787+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:59:47.787+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:59:48.044+0000] {logging_mixin.py:151} INFO - [2025-08-03T10:59:48.025+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T10:59:48.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T10:59:48.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.357 seconds
[2025-08-03T11:00:18.579+0000] {processor.py:157} INFO - Started process (PID=1249) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T11:00:18.586+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T11:00:18.588+0000] {logging_mixin.py:151} INFO - [2025-08-03T11:00:18.587+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T11:00:18.744+0000] {logging_mixin.py:151} INFO - [2025-08-03T11:00:18.734+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T11:00:18.746+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T11:00:18.795+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.219 seconds
[2025-08-03T11:00:48.935+0000] {processor.py:157} INFO - Started process (PID=1260) to work on /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T11:00:48.938+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_spark_db_dag.py for tasks to queue
[2025-08-03T11:00:48.940+0000] {logging_mixin.py:151} INFO - [2025-08-03T11:00:48.939+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T11:00:49.132+0000] {logging_mixin.py:151} INFO - [2025-08-03T11:00:49.124+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_spark_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_spark_db_dag.py", line 68, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 600, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
[2025-08-03T11:00:49.134+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_spark_db_dag.py
[2025-08-03T11:00:49.177+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_spark_db_dag.py took 0.251 seconds
